### ISSUE TITLE
VS Crashes when pasting

### ISSUE THREAD

**Issue by srgloureiro** [mtubek/FastGitBranchX64#6]
**Describe the bug**
Pasting makes Visual Studio Community 2022 crash.

**To Reproduce**
Grab some text from somewhere.
Then past into the Branch name text field.
My first part is **feature**
I have the second part field empty.

**Expected behavior**
not to crash

**Desktop (please complete the following information):**
Windows 11

**Comment by Jan-Magerl** [comment]
I have a similar Issue:
If i enter special characters like "ü" in the Branch Name the Window disappears.
If i bring it back and press Cancel, Visual studio crashes

**Comment by mtubek** [comment]
Modified validation to accept diacritical marks with info message "We do not recommend using diacritical marks in branch name"
